-- SkateShop Official Inventory Import
-- 100 Real Skateboarding Products
-- Database Compatibility: products table

INSERT INTO products (title, brand, price, discount_price, quantity, category, description, image_url, is_marketplace) VALUES
('Baker Brand Logo Deck 8.0', 'Baker', 69.99, NULL, 15, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Girl Sean Malto OG Deck 8.12', 'Girl', 65.99, NULL, 20, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Chocolate Chunk Deck 8.0', 'Chocolate', 65.99, NULL, 18, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Zero Jamie Thomas Cross 8.25', 'Zero', 64.99, NULL, 12, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('DGK Boo Johnson Ghetto 8.1', 'DGK', 68.99, NULL, 10, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Primitive P-Rod Eagle 8.0', 'Primitive', 74.99, NULL, 14, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Santa Cruz Screaming Hand 8.25', 'Santa Cruz', 69.99, NULL, 22, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Powell Peralta Ripper 8.5', 'Powell Peralta', 75.99, NULL, 8, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Element Section Deck 8.0', 'Element', 59.99, NULL, 25, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Anti-Hero Eagle Deck 8.25', 'Anti-Hero', 69.99, NULL, 16, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Krooked Ray Barbee Deck 8.38', 'Krooked', 72.99, NULL, 11, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Real Ishod Wair Twin 8.25', 'Real', 74.99, NULL, 13, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Creature Logo Deck 8.5', 'Creature', 69.99, NULL, 9, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Plan B Team Deck 8.0', 'Plan B', 64.99, NULL, 17, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Almost Mullen Uber 8.0', 'Almost', 89.99, NULL, 6, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Enjoi Panda Deck 8.0', 'Enjoi', 62.99, NULL, 19, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Blind Reaper Deck 8.0', 'Blind', 59.99, NULL, 21, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Alien Workshop Believe 8.12', 'Alien Workshop', 68.99, NULL, 12, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Toy Machine Monster 8.25', 'Toy Machine', 65.99, NULL, 14, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Foundation Star & Moon 8.0', 'Foundation', 64.99, NULL, 15, 'Decks', '7-ply North American maple construction with top-tier pop and durability. Official professional model.', '', 0),
('Indy Stage 11 Standard 139', 'Independent', 49.99, NULL, 30, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Indy Stage 11 Hollow 144', 'Independent', 54.99, NULL, 25, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Indy Forged Titanium 149', 'Independent', 79.99, NULL, 10, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Thunder Polished Hi 147', 'Thunder', 48.99, NULL, 28, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Thunder Hollow Lights 148', 'Thunder', 59.99, NULL, 18, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Thunder Titanium Lights 149', 'Thunder', 78.99, NULL, 12, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Venture Polished Hi 5.2', 'Venture', 45.99, NULL, 32, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Venture V-Hollow 5.2', 'Venture', 55.99, NULL, 20, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Venture V-Titanium 5.6', 'Venture', 74.99, NULL, 14, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Ace Classic 44', 'Ace Trucks', 49.99, NULL, 24, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Ace AF1 55', 'Ace Trucks', 59.99, NULL, 16, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Krux K5 Standard 8.0', 'Krux', 44.99, NULL, 26, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Krux DLK 8.25', 'Krux', 49.99, NULL, 22, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Tensor Mag Light 5.25', 'Tensor', 69.99, NULL, 15, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Tensor Aluminum 5.5', 'Tensor', 39.99, NULL, 28, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Royal Standard 139', 'Royal', 45.99, NULL, 20, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Royal Inverted 144', 'Royal', 54.99, NULL, 18, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Silver M-Class 8.0', 'Silver', 44.99, NULL, 22, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Destructo Mid 5.25', 'Destructo', 42.99, NULL, 16, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Theeve TiAX 5.25', 'Theeve', 59.99, NULL, 14, 'Trucks', 'Durable and lightweight performance trucks for all types of skateboarding. Features superior turning geometry.', '', 0),
('Spitfire Formula 4 Classic', 'Spitfire', 44.99, NULL, 40, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Spitfire F4 Conical Full', 'Spitfire', 46.99, NULL, 35, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Spitfire Bighead 53mm', 'Spitfire', 34.99, NULL, 50, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Bones STF Retros 52mm', 'Bones', 39.99, NULL, 38, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Bones SPF Clear 54mm', 'Bones', 42.99, NULL, 25, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Bones 100s V4 Wide 53mm', 'Bones', 29.99, NULL, 45, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Ricta Clouds 78a 54mm', 'Ricta', 36.99, NULL, 30, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Ricta Rapido 52mm', 'Ricta', 39.99, NULL, 22, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('OJ Super Juice 60mm', 'OJ', 44.99, NULL, 20, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('OJ Elite Hardline 54mm', 'OJ', 42.99, NULL, 18, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Snot Wheels 53mm', 'Snot Wheels', 35.99, NULL, 15, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Dial Tone Wheels 52mm', 'Dial Tone', 34.99, NULL, 16, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Satori Movement 54mm', 'Satori', 38.99, NULL, 14, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Hubba Hideout 52mm', 'Hubba', 32.99, NULL, 12, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Pig Wheels Conical 53mm', 'Pig Wheels', 33.99, NULL, 25, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Autobahn Dual Duro 54mm', 'Autobahn', 39.99, NULL, 18, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Wayward Wheels 52mm', 'Wayward', 36.99, NULL, 20, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Bones ATF Rough Riders 56mm', 'Bones', 44.99, NULL, 22, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Spitfire Chargers 80hd', 'Spitfire', 42.99, NULL, 28, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Ricta Chrome Core 53mm', 'Ricta', 38.99, NULL, 15, 'Wheels', 'High-performance urethane formula offering unmatched flatspot resistance and a smooth anti-stick slide.', '', 0),
('Bones Reds Bearings', 'Bones', 19.99, NULL, 100, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Bones Swiss Bearings', 'Bones', 69.99, NULL, 30, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Bones Swiss Ceramics', 'Bones', 159.99, NULL, 10, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Bronson Speed Co G3', 'Bronson Speed Co', 29.99, NULL, 45, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Bronson Speed Co RAW', 'Bronson Speed Co', 39.99, NULL, 35, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Indy Genuine Bearings', 'Independent', 17.99, NULL, 50, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Andale Pro Rated Bearings', 'Andale', 24.99, NULL, 25, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Spitfire Burners', 'Spitfire', 18.99, NULL, 40, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Shake Junt Pro Bearings', 'Shake Junt', 22.99, NULL, 30, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Cortina Precision Bearings', 'Cortina', 28.99, NULL, 20, 'Bearings', 'Precision engineered skate bearings. Pre-lubricated for maximum speed, longevity, and easy maintenance.', '', 0),
('Thrasher Flame Hoodie', 'Thrasher', 69.99, NULL, 35, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Vans Classic Tee', 'Vans', 24.99, NULL, 60, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Nike SB Icon Pullover', 'Nike SB', 65.99, NULL, 40, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Adidas Track Jacket', 'Adidas', 79.99, NULL, 25, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Santa Cruz Dot Longsleeve', 'Santa Cruz', 34.99, NULL, 45, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Spitfire Bighead T-Shirt', 'Spitfire', 25.99, NULL, 55, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Indy Cross Hoodie', 'Independent', 59.99, NULL, 30, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Baker Brand Logo Tee', 'Baker', 26.99, NULL, 40, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Primitive Dirty P Hoodie', 'Primitive', 64.99, NULL, 28, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Girl OG Logo Tee', 'Girl', 25.99, NULL, 42, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Volcom Skate Vitals Pants', 'Volcom', 59.99, NULL, 20, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Dickies 874 Work Pants', 'Dickies', 49.99, NULL, 50, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Levis Skateboarding 501', 'Levis', 69.99, NULL, 35, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Polar Big Boy Jeans', 'Polar Skate Co', 119.99, NULL, 15, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('HUF Plantlife Socks', 'HUF', 14.99, NULL, 80, 'Apparel', 'Premium quality skate apparel. Designed for comfort, durability, and classic skateboarding style.', '', 0),
('Mob Grip Tape Black', 'Mob Grip', 6.99, NULL, 150, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Jessup Grip Tape', 'Jessup', 5.99, NULL, 120, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Shake Junt Grip Tape', 'Shake Junt', 8.99, NULL, 80, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Indy 7/8 Allen Hardware', 'Independent', 3.99, NULL, 200, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Shortys Silverados 1 Hardware', 'Shortys', 4.99, NULL, 150, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Spitfire T3 Skate Tool', 'Spitfire', 19.99, NULL, 40, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Indy Genuine Parts Tool', 'Independent', 18.99, NULL, 35, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Bones Speed Cream', 'Bones', 7.99, NULL, 100, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Shoe Goo Clear', 'Shoe Goo', 8.99, NULL, 90, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Ninja Bearing Press', 'Ninja', 49.99, NULL, 15, 'Accesories', 'Essential skate gear designed to keep your setup dialed and performing at its absolute best.', '', 0),
('Dakine Skate Backpack', 'Dakine', 75.99, NULL, 25, 'Other', 'High quality skateboarding gear built to withstand the demands of modern street and park riding.', '', 0),
('Nixon Time Teller Watch', 'Nixon', 100.00, NULL, 12, 'Other', 'High quality skateboarding gear built to withstand the demands of modern street and park riding.', '', 0),
('Vans Old Skool Pro', 'Vans', 74.99, NULL, 45, 'Other', 'High quality skateboarding gear built to withstand the demands of modern street and park riding.', '', 0),
('Nike SB Dunk Low Pro', 'Nike SB', 110.00, NULL, 10, 'Other', 'High quality skateboarding gear built to withstand the demands of modern street and park riding.', '', 0),
('Emerica Dickson Shoes', 'Emerica', 84.99, NULL, 30, 'Other', 'High quality skateboarding gear built to withstand the demands of modern street and park riding.', '', 0);
